import{i as y,S as I,a as L}from"./assets/vendor-95dc692e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function w(s,r="center"){y.info({title:"Info",message:s,position:r})}function c(s,r="center"){y.error({title:"Error",message:s,position:r})}console.log("renderData:v.2.03");var x=new I(".gallery a",{captionsData:"alt",captionDelay:250});const E=async s=>{if(s.length===0)return;let r="";document.querySelector(".gallery-list")!=null&&(r=document.querySelector(".gallery-list").innerHTML),r+=await s.map(a=>`
            <li class="gallery-item">
                <a class="gallery-link" href="${a.largeImageURL}">
                    <img class="gallery-image" src="${a.webformatURL}" alt="${a.tags}" />
                </a>
                <ul class="item-info">
                    <li><h3 class="item-title">Likes</h3>    <p class="item-text">${a.likes}</p>
                    <li><h3 class="item-title">Views</h3>    <p class="item-text">${a.views}</p>
                    <li><h3 class="item-title">Comments</h3> <p class="item-text">${a.comments}</p>
                    <li><h3 class="item-title">Downloads</h3><p class="item-text">${a.downloads}</p>
                </ul>
            </li>
        `).join(""),gallery.innerHTML=`<ul class="gallery-list">${r}</ul>`,x.refresh()};console.log("renderData:loaded...");const v=async(s,r,a=15)=>{console.log(`pixabay:search=>[${s}]`);const n="https://pixabay.com/api/",t={key:"42700764-e859e8fc9280be2dbaa9956c4",q:s,safesearch:!0,image_type:"photo",orientation:"horizontal",per_page:a,page:r};try{const o=n,b={params:t};return await L.get(o,b)}catch(o){throw console.error("pixabay:Error fetching images:",o),o}finally{console.log("pixabay:search.end;")}};console.log("pixaBay.api:loaded...");let m=1,l="";const $=document.getElementById("searchForm"),d=document.getElementById("searchInput"),g=document.getElementById("submit");g.disabled=!0;const B=document.getElementById("gallery"),p=document.getElementById("loading-indicator"),i=document.getElementById("load-more-btn");d.addEventListener("input",s=>{g.disabled=d.value.trim()===""});$.addEventListener("submit",async s=>{if(s.preventDefault(),B.innerHTML="",h(),l=d.value.trim(),l==="")return console.log("Please enter a search term."),c("Please enter a search term.");await f(1)});i.addEventListener("click",async()=>{m++,await f(m)});async function f(s){h();try{i.style.display="none";const n=(await v(l,s,15)).data,e=n.hits;E(e);const t=n.totalHits||0;if(console.log("totalHits:",t),t===0){const o=`main: Sorry, there are no images matching your search query: [${l}]. Please try again!`;return u(),c(o)}if(t<=s*15)return w("We're sorry, but you've reached the end of search results.");i.style.display="block"}catch(r){c(r.message)}finally{u()}}function h(){p.style.display="block",i.style.display="none"}function u(){p.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
